name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main  # Or any other branch you deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
        cache: maven

    - name: Build with Maven
      run: mvn clean package --file pom.xml

    - name: Upload JAR to EC2
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "target/*.jar"
        target: "/home/${{ secrets.EC2_USER }}/app/"

    - name: Start Spring Boot on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          pkill -f 'java -jar' || true
          cd /home/${{ secrets.EC2_USER }}/app/
          nohup java -jar *.jar > app.log 2>&1 &
